variable "env_name" {}
variable "compartment_id" {}
variable "root_compartment_id" {}
variable "private_subnet_id" {}
variable "oke_cluster_id" {}
variable "k8s_version" {}
variable "node_os_version" {}
variable "node_size" {}
variable "node_shape" {}
variable "node_ocpus" {}
variable "node_memory_in_gbs" {}
variable "node_boot_volume_size_in_gbs" {}
